In [10]:
import numpy as np
x = [[170, 240, 10, 80, 150],
     [230, 50, 70, 140, 160],
     [40, 60, 130, 200, 220],
     [100, 200, 190, 210, 30],
     [110, 180, 250, 20, 90]]
x = np.array(x, dtype=np.uint8)

In [11]:
#線性濾波器
#ones:產生一個3*3的shape 裡面都是1
#再把裡面每個數字除以9
mask = np.ones((3,3)) /9
#print(mask)

#取出x的大小
rows, cols = x.shape
#創造一個全為0的空間，大小事rows*cols
result = np.zeros((rows,cols))
for i in range(1,rows-1):
    for j in range(1,cols-1):
        #(i-1:i+2,j-1:j+2): 取i-1~i+1 和 j-1~j+1
        result[i,j]= np.sum(x[i-1:i+2,j-1:j+2]*mask)

print(result)


[[  0.           0.           0.           0.           0.        ]
 [  0.         111.11111111 108.88888889 128.88888889   0.        ]
 [  0.         118.88888889 138.88888889 150.           0.        ]
 [  0.         140.         160.         148.88888889   0.        ]
 [  0.           0.           0.           0.           0.        ]]


In [12]:
import scipy.ndimage as ndi
#mode=‘constant‘代表填入常數值之填補，內定值是0之填補
result2=ndi.convolve(x,mask,mode='constant')
print(result2)

[[ 76  85  65  67  58]
 [ 87 111 108 128 105]
 [ 75 118 138 150 106]
 [ 76 140 160 148  85]
 [ 65 114 116  87  38]]
